
const anecdotes = [
    'If it hurts, do it more often',
    'Adding manpower to a late software project makes it later!',
    'The first 90 percent of the code accounts for the first 90 percent of the development time...The remaining 10 percent of the code accounts for the other 90 percent of the development time.',
    'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.',
    'Premature optimization is the root of all evil.',
    'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.',
    'Hiring people to write code to sell is not the same as hiring people to design and build durable, usable, dependable software.',
    `No matter what the problem is, it's always a people problem.`,
    `Experience doesn't necessarily teach anything.`,
    'Conceptual integrity is the most important consideration in system design.',
    'Every big computing disaster has come from taking too many ideas and putting them in one place.',
    'When debugging, novices insert corrective code; experts remove defective code.',
    `... programming requires more concentration than other activities. It's the reason programmers get upset about 'quick interruptions' - such interruptions are tantamount to asking a juggler to keep three balls in the air and hold your groceries at the same time."`,
    'Always code as if the person who ends up maintaining your code will be a violent psychopath who knows where you live.',
    `If something is worth doing once, it's worth building a tool to do it.`,
    'The perfect project plan is possible if one first documents a list of all the unknowns.',
    'I have always found that plans are useless, but planning is indispensable.',
    `You can't have great software without a great team, and most software teams behave like dysfunctional families.`,
    'If you cannot grok the overall structure of a program while taking a shower, you are not ready to code it.',
    'Increasingly, people seem to misinterpret complexity as sophistication, which is baffling --- the incomprehensible should cause suspicion rather than admiration.',
    'Make everything as simple as possible, but not simpler.',
    'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.',
    'One principle problem of educating software engineers is that they will not use a new method until they believe it works and, more importantly, that they will not believe the method will work until they see it for themselves.',
    'Correctness is clearly the prime quality. If a system does not do what it is supposed to do, then everything else about it matters little.',
    'The competent programmer is fully aware of the strictly limited size of his own skull; therefore he approaches the programming task in full humility, and among other things he avoids clever tricks like the plague.',
    'More computing sins are committed in the name of efficiency (without necessarily achieving it) than for any other single reason - including blind stupidity.',
    'Simplicity is prerequisite for reliability',
    'The best performance improvement is the transition from the nonworking state to the working state.',
    'A good way to stay flexible is to write less code.',
    `It's hard enough to find an error in your code when you're looking for it; it's even harder when you've assumed your code is error-free.`,
    '... with proper design, the features come cheaply. This approach is arduous, but continues to succeed.',
    'Simplicity is the soul of efficiency.',
    'Simple things should be simple, complex things should be possible.',
    'When to use iterative development? You should use iterative development only on projects that you want to succeed.',
    'Good judgment comes from experience, and experience comes from bad judgment.',
    'Optimism is an occupational hazard of programming: feedback is the treatment.',
    'Better train people and risk they leave - than do nothing and risk they stay.'
]

export default anecdotes